<?php
/**
 * Created by PhpStorm.
 * User: ELACHI
 * Date: 10/29/2016
 * Time: 10:05 AM
 */

namespace Models;


use Framework\Base\Model;
use Framework\TinyMvc;
use Globals\AppConstants;

class StageMember extends Model
{
    protected function getTableName()
    {
        return 'stagemembers'; // TODO: Change the autogenerated stub
    }


    public static function haveCompletedStage(Member $member, MatrixStage $stage){
        $left_index = $member->getLeftIndex();
        $right_index = $member->getRightIndex();

        $block = $member->getLevel() + $stage->getBlock();

        $sql = "SELECT COUNT(id) AS no FROM stagemembers WHERE (left_index BETWEEN $left_index AND $right_index)";
        if($stage->getId() == AppConstants::STAGE_ONE){
            $sql.= " AND (`block` = $block)";
        }
        $result = \R::getAll($sql);

        $result = $result[0]['no'] == $stage->getCompleteLineUp();
        return $result;
    }

    public static function getDownlines(Member $member, MatrixStage $stage){
        $left = $member->getLeftIndex(); $right = $member->getRightIndex();
        $stage_id = $stage->getId();

        $sql = "SELECT membership_id, parent_id, left_index, right_index, username, `block` FROM stagemembers
                WHERE (left_index BETWEEN $left AND $right) AND stage_id = $stage_id ORDER BY left_index ASC;";

        $result = \R::getAll($sql);

        return $result;
    }


    protected $membership_id;

    protected $fistname;

    protected $lastname;

    protected $username;

    protected $left_index;

    protected $right_index;

    protected $parent_id;

    protected $stage_id;

    protected $block;

    public function setBlock($block)
    {
        $this->block = $block;
        return $this;
    }

    public function setLeftIndex($left_index)
    {
        $this->left_index = $left_index;
        return $this;
    }

    public function setMembershipId($membership_id)
    {
        $this->membership_id = $membership_id;
        return $this;
    }

    public function setParentId($parent_id)
    {
        $this->parent_id = $parent_id;
        return $this;
    }

    public function setRightIndex($right_index)
    {
        $this->right_index = $right_index;
        return $this;
    }

    public function setStageId($stage_id)
    {
        $this->stage_id = $stage_id;
        return $this;
    }

    public function setFistname($fistname)
    {
        $this->fistname = $fistname;
        return $this;
    }

    public function setLastname($lastname)
    {
        $this->lastname = $lastname;
        return $this;
    }

    public function setUsername($username)
    {
        $this->username = $username;
        return $this;
    }

    public function getBlock()
    {
        return $this->block;
    }

    public function getLeftIndex()
    {
        return $this->left_index;
    }

    public function getMembershipId()
    {
        return $this->membership_id;
    }

    public function getParentId()
    {
        return $this->parent_id;
    }

    public function getRightIndex()
    {
        return $this->right_index;
    }

    public function getStageId()
    {
        return $this->stage_id;
    }

}